# Generated by Django 4.0.6 on 2022-07-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=100)),
                ('imageUrl', models.ImageField(default='default.jpg', upload_to='image-files')),
                ('imageDetails', models.CharField(max_length=100)),
            ],
        ),
    ]
