# Generated by Django 4.0.6 on 2022-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imageUrl',
            field=models.ImageField(upload_to='image-files'),
        ),
    ]
